# If someone with write access comments "/ok-to-test" on a pull request, emit a repository_dispatch event
name: Ok To Test

on:
  issue_comment:
    types: [created]

jobs:
  ok-to-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check for args
        run: |
            body=${{ github.event.comment.body }};
            REGEX='\/ok-to-test (tags="([^"\\]*)")';
            if [[ $body =~ $REGEX ]]; then
              echo all: "$BASH_REMATCH[0]"
              echo "yay"
            else
              echo 404
            fi
            exit 0;
