# If someone with write access comments "/ok-to-test" on a pull request, emit a repository_dispatch event
name: Ok To Test

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - labeled

jobs:
  check-labels:
    name: Check for Test Plan Approved label
    runs-on: ubuntu-latest
    steps:
      - name: Dump the client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event) }}
        run: echo "$PAYLOAD_CONTEXT"

      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          # Needs to have a Test Plan Approved label if not part of any of the pods below
          any_of: ok-to-test
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  parse-tags:
    needs: [check-labels]
    if: success()
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    outputs:
      tags: ${{ steps.checkAll.outputs.tags }}
      matrix: ${{ steps.checkAll.outputs.matrix }}
    steps:
      - name: Get tags
        uses: actions-ecosystem/action-regex-match@v2
        id: getTags
        with:
          text: ${{ github.event.issue.body }}
          regex: '^/ok-to-test tags="([^"]*)"'

      # - name: Parse tags
      #   id: parseTags
      #   run: |
      #       body='${{ github.event.issue.body }}';
      #       REGEX='/ok-to-test tags="([^"]*)"';
      #       if [[ $body =~ $REGEX ]]; then
      #         echo "tags=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
      #         echo "yay"
      #       else
      #         echo 404
      #       fi

      - name: Parse tags
        id: parseTags
        run: |
              echo "tags=${{ steps.getTags.outputs.match }}" >> $GITHUB_OUTPUT

      - name: Add a comment on the PR with tags documentation link
        if: steps.parseTags.outcome != 'success'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            The provided command lacks proper tags. Please execute '/ok-to-test' again, specifying the tags you want to include or use `/ok-to-test tags="@tag.All"` to run all specs.
            Explore the tags documentation [here](https://www.notion.so/appsmith/Ok-to-test-With-Tags-7c0fc64d4efb4afebf53348cd6252918)

      - name: Stop the workflow run if tags are not present
        if: steps.parseTags.outcome != 'success'
        run: exit 1

      - name: Check if @tag.All is present in tags
        id: checkAll
        run: |
          tags="${{ steps.parseTags.outputs.tags }}"
          if [[ ($tags == *"ALL"* || $tags == *"All"*  || $tags == *"all"*) && $tags != *"@tag.All"* ]]; then
            echo "invalid_tags_all=$tags" >> $GITHUB_OUTPUT
          elif [[ $tags == *"@tag.All"* ]]; then
            echo "tags=" >> $GITHUB_OUTPUT
            echo "matrix=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]" >> $GITHUB_OUTPUT
          else
            echo "tags=$tags" >> $GITHUB_OUTPUT
            echo "matrix=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]" >> $GITHUB_OUTPUT
          fi

      - name: Add comment to use correct @tag.All format 
        if: steps.checkAll.outputs.invalid_tags_all != ''
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Please use `/ok-to-test tags="@tag.All"` to run all specs.
            Explore the tags documentation [here](https://www.notion.so/appsmith/Ok-to-test-With-Tags-7c0fc64d4efb4afebf53348cd6252918)
      
      - name: Stop the workflow run if given @tag.All format is wrong
        if: steps.checkAll.outputs.invalid_tags_all != ''
        run: exit 1

      # tags is set to empty string if @tag.All is given in step - Check if @tag.All is present in tags
      - name: Add suggestion in the PR on using @tag.All 
        if: steps.checkAll.outputs.tags == ''
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Whoa, @tag.All spotted in your test suite! 🚀
            While @tag.All is cool, like a catch-all net, why not try specific tags? 🏷️
            Narrow down your suite with specific tags for quicker and more accurate tests! 🚀 Less waiting, more zipping through tests like a ninja!
            Explore the tags documentation [here](https://www.notion.so/appsmith/Ok-to-test-With-Tags-7c0fc64d4efb4afebf53348cd6252918)

      # This step creates a comment on the PR with a link to this workflow run.
      # - name: Add a comment on the PR with link to workflow run
      #   uses: peter-evans/create-or-update-comment@v3
      #   with:
      #     issue-number: ${{ github.event.issue.number }}
      #     body: |
      #       Tests running at: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>.
      #       Workflow: `${{ github.workflow }}`.
      #       Tags: `${{ steps.checkAll.outputs.tags }}`.

  ok-to-test:
    needs: [parse-tags]
    if: success()
    uses: ./.github/workflows/test.yml
    with:
      tags: ${{ needs.parse-tags.outputs.tags}}
      matrix: ${{ needs.parse-tags.outputs.matrix}}
